name: ml-nano
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
      - tensorflow-cpu==2.15.0
      - keras==2.15.0
      - opencv-python
      - ultralytics
      - torchvision
