name: ml-nano
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipywidgets
  - pytorch
  - torchvision
  - pip
  - pip:
      - opencv-python
      - ultralytics
